# Generated by Django 5.0.3 on 2024-03-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id_livreur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_liv', models.CharField(max_length=100)),
                ('prenom_liv', models.CharField(max_length=100)),
                ('tel_liv', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id_medecin', models.AutoField(primary_key=True, serialize=False)),
                ('nom_medecin', models.CharField(max_length=100)),
                ('prenom_medecin', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('num_telM', models.CharField(max_length=15)),
                ('adr_mailM', models.EmailField(max_length=254)),
                ('adresse_cabinet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pr', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('qte_stock', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('nom_patient', models.CharField(max_length=100)),
                ('prenom_patient', models.CharField(max_length=100)),
                ('adressePa', models.CharField(max_length=255)),
                ('adr_mail', models.EmailField(max_length=254)),
                ('num_tel', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id_pharmacie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app3.produit')),
                ('dosage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPharmaceutique',
            fields=[
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app3.produit')),
                ('marque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('nom_patient', models.CharField(max_length=100)),
                ('prenom_patient', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('id_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.medecin')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueMedical',
            fields=[
                ('id_historiqueM', models.AutoField(primary_key=True, serialize=False)),
                ('id_ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.ordonnance')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePharmaceutique',
            fields=[
                ('id_historiqueP', models.AutoField(primary_key=True, serialize=False)),
                ('dateP', models.DateField()),
                ('descriptionP', models.TextField()),
                ('id_ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.ordonnance')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.patient')),
                ('id_pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.produit')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.patient')),
                ('id_pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie')),
            ],
        ),
    ]
