# Generated by Django 5.0.3 on 2024-03-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('adr_mail', models.EmailField(max_length=254)),
                ('num_tel', models.CharField(max_length=15)),
                ('date', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
                ('adresse', models.CharField(max_length=1)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
