# Generated by Django 5.0.3 on 2024-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nom_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
