# Generated by Django 5.0.3 on 2024-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_alter_login_nom_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='adr_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='adresse',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='num_tel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='sexe',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
