# Generated by Django 5.0.3 on 2024-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_alter_login_adr_mail_alter_login_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
