# Generated by Django 5.0.3 on 2024-03-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_alter_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='prenom_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='sexe',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
