# Generated by Django 5.0.3 on 2024-03-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0006_login_prenom_utilisateur_medecin_date_medecin_sexe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
