# Generated by Django 5.0.3 on 2024-03-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0007_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='heure_fermeture',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='heure_ouverture',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='nom_responsable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
