# Generated by Django 5.0.3 on 2024-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0008_alter_pharmacie_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nom_utilisateur',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
