# Generated by Django 5.0.3 on 2024-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0009_alter_login_nom_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='nom_medecin',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
