# Generated by Django 5.0.3 on 2024-03-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0010_alter_medecin_nom_medecin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='login',
            unique_together={('nom_utilisateur', 'role')},
        ),
    ]
