# Generated by Django 5.0.3 on 2024-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0011_alter_login_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nom_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom_medecin',
            field=models.CharField(max_length=100),
        ),
    ]
