# Generated by Django 5.0.3 on 2024-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0012_alter_login_nom_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='login',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='login',
            name='nom_utilisateur',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
