# Generated by Django 5.0.3 on 2024-03-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0013_alter_login_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_medecin',
        ),
        migrations.RemoveField(
            model_name='historiquemedical',
            name='id_patient',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_patient',
        ),
        migrations.RemoveField(
            model_name='historiquepharmaceutique',
            name='id_patient',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_pharmacie',
        ),
        migrations.RemoveField(
            model_name='historiquepharmaceutique',
            name='id_pharmacie',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_produit',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Pharmacie',
        ),
    ]
