# Generated by Django 5.0.3 on 2024-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0014_delete_login_remove_ordonnance_id_medecin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='utillisateur',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=100)),
                ('prenom_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='historiquemedical',
            name='id_ordonnance',
        ),
        migrations.RemoveField(
            model_name='historiquepharmaceutique',
            name='id_ordonnance',
        ),
        migrations.DeleteModel(
            name='Livreur',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produitpharmaceutique',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='HistoriqueMedical',
        ),
        migrations.DeleteModel(
            name='HistoriquePharmaceutique',
        ),
        migrations.DeleteModel(
            name='Ordonnance',
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.DeleteModel(
            name='ProduitPharmaceutique',
        ),
    ]
