# Generated by Django 5.0.3 on 2024-03-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0015_utillisateur_remove_commande_id_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueMedical',
            fields=[
                ('id_historiqueM', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePharmaceutique',
            fields=[
                ('id_historiqueP', models.AutoField(primary_key=True, serialize=False)),
                ('dateP', models.DateField()),
                ('descriptionP', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id_livreur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_liv', models.CharField(max_length=100)),
                ('prenom_liv', models.CharField(max_length=100)),
                ('tel_liv', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100, null=True, unique=True)),
                ('prenom_utilisateur', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('adr_mail', models.EmailField(max_length=254, null=True)),
                ('num_tel', models.CharField(max_length=15, null=True)),
                ('date', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
                ('adresse', models.CharField(max_length=1, null=True)),
                ('role', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id_medecin', models.AutoField(primary_key=True, serialize=False)),
                ('nom_medecin', models.CharField(max_length=100)),
                ('prenom_medecin', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('num_telM', models.CharField(max_length=15)),
                ('adr_mailM', models.EmailField(max_length=254)),
                ('adresse_cabinet', models.CharField(max_length=255)),
                ('date', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pr', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('qte_stock', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('nom_patient', models.CharField(max_length=100)),
                ('prenom_patient', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('id_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.medecin')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('nom_patient', models.CharField(max_length=100)),
                ('prenom_patient', models.CharField(max_length=100)),
                ('adressePa', models.CharField(max_length=255)),
                ('adr_mail', models.EmailField(max_length=254)),
                ('num_tel', models.CharField(max_length=15)),
                ('sexe', models.CharField(max_length=1)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id_pharmacie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('nom_responsable', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('heure_ouverture', models.TimeField(null=True)),
                ('heure_fermeture', models.TimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='utillisateur',
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app3.produit')),
                ('dosage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPharmaceutique',
            fields=[
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app3.produit')),
                ('marque', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='id_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.produit'),
        ),
        migrations.AddField(
            model_name='historiquepharmaceutique',
            name='id_ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.ordonnance'),
        ),
        migrations.AddField(
            model_name='historiquemedical',
            name='id_ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.ordonnance'),
        ),
        migrations.AddField(
            model_name='historiquepharmaceutique',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AddField(
            model_name='historiquemedical',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AddField(
            model_name='historiquepharmaceutique',
            name='id_pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie'),
        ),
    ]
