# Generated by Django 5.0.3 on 2024-03-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0016_commande_historiquemedical_historiquepharmaceutique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='nom_utilisateur',
        ),
    ]
