# Generated by Django 5.0.3 on 2024-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0017_remove_login_nom_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='nom_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
