# Generated by Django 5.0.3 on 2024-03-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0018_login_nom_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='tel',
        ),
    ]
