# Generated by Django 5.0.3 on 2024-03-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0020_alter_login_nom_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
