# Generated by Django 5.0.3 on 2024-03-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0021_pharmacie_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='nom_utilisateur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
