# Generated by Django 5.0.3 on 2024-03-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0022_alter_login_nom_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id_produit',
        ),
        migrations.RemoveField(
            model_name='historiquepharmaceutique',
            name='dateP',
        ),
        migrations.RemoveField(
            model_name='historiquepharmaceutique',
            name='descriptionP',
        ),
        migrations.RemoveField(
            model_name='historiquepharmaceutique',
            name='id_patient',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='nom_liv',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='prenom_liv',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='tel_liv',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom_pr',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='produitpharmaceutique',
            name='produit',
        ),
        migrations.AddField(
            model_name='livreur',
            name='nom_livreur',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='livreur',
            name='prenom_livreur',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='livreur',
            name='tel_livreur',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='medicament',
            name='produit_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app3.produit'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='id_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='nom_medecin',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='prenom_medecin',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='adresse_pharmacie',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='mail_pharmacie',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='nom_pharmacie',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='tel_pharmacie',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='produitpharmaceutique',
            name='produit_ptr',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app3.produit'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id_commande',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id_pharmacie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie'),
        ),
        migrations.AlterField(
            model_name='historiquemedical',
            name='id_historiqueM',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historiquemedical',
            name='id_ordonnance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.ordonnance'),
        ),
        migrations.AlterField(
            model_name='historiquemedical',
            name='id_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AlterField(
            model_name='historiquepharmaceutique',
            name='id_historiqueP',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historiquepharmaceutique',
            name='id_ordonnance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.ordonnance'),
        ),
        migrations.AlterField(
            model_name='historiquepharmaceutique',
            name='id_pharmacie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='id_livreur',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='adr_mailM',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='adresse_cabinet',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='id_medecin',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom_medecin',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='num_telM',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='prenom_medecin',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id_medecin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.medecin'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id_ordonnance',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id_produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.produit'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='nom_patient',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='prenom_patient',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_patient',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='num_tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='heure_fermeture',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='heure_ouverture',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='id_pharmacie',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='nom_responsable',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id_produit',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qte_stock',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='produitpharmaceutique',
            name='marque',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
