# Generated by Django 5.0.3 on 2024-03-20 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0023_remove_commande_id_produit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livreur',
            old_name='nom_livreur',
            new_name='nom_liv',
        ),
        migrations.RenameField(
            model_name='livreur',
            old_name='prenom_livreur',
            new_name='prenom_liv',
        ),
        migrations.RenameField(
            model_name='livreur',
            old_name='tel_livreur',
            new_name='tel_liv',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='produit_ptr',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='pharmacie',
            old_name='mail_pharmacie',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='pharmacie',
            old_name='nom_pharmacie',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='pharmacie',
            old_name='tel_pharmacie',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='nom_produit',
            new_name='nom_pr',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='type_produit',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='produitpharmaceutique',
            old_name='produit_ptr',
            new_name='produit',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='adresse_pharmacie',
        ),
        migrations.AddField(
            model_name='commande',
            name='id_produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.produit'),
        ),
        migrations.AddField(
            model_name='historiquepharmaceutique',
            name='dateP',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='historiquepharmaceutique',
            name='descriptionP',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='historiquepharmaceutique',
            name='id_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.patient'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='sexe',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='adresse',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
