# Generated by Django 5.0.3 on 2024-03-20 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0024_rename_nom_livreur_livreur_nom_liv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pharmacie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='adresse',
            field=models.CharField(default='valeur par défaut', max_length=255, null=True),
        ),
    ]
