# Generated by Django 5.0.3 on 2024-03-20 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0025_produit_pharmacie_alter_pharmacie_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_produit',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_pr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.pharmacie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('medicament', 'Médicament'), ('produit_pharmaceutique', 'Produit Pharmaceutique')], max_length=100),
        ),
    ]
