# Generated by Django 5.0.3 on 2024-03-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0026_alter_produit_id_produit_alter_produit_nom_pr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='dosage',
            new_name='dosage_edicaent',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='produit',
            new_name='produit_ptr',
        ),
        migrations.RenameField(
            model_name='produitpharmaceutique',
            old_name='produit',
            new_name='produit_ptr',
        ),
        migrations.AddField(
            model_name='produit',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
