# Generated by Django 5.0.3 on 2024-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0027_rename_dosage_medicament_dosage_edicaent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('medicament', 'Médicament'), ('produit_pharmaceutique', 'ProduitPharmaceutique')], max_length=100),
        ),
    ]
