# Generated by Django 5.0.3 on 2024-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0028_alter_produit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitpharmaceutique',
            old_name='marque',
            new_name='marque_produit',
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
