# Generated by Django 5.0.3 on 2024-03-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0029_rename_marque_produitpharmaceutique_marque_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='marque',
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
