# Generated by Django 5.0.3 on 2024-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0030_remove_produit_dosage_remove_produit_marque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('Pharmaceutique', 'Produit Pharmaceutique'), ('Medicament', 'Médicament')], max_length=100),
        ),
    ]
