# Generated by Django 5.0.3 on 2024-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0031_alter_produit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitpharmaceutique',
            old_name='marque_produit',
            new_name='marque_produitpha',
        ),
        migrations.AddField(
            model_name='produit',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque_produit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
