# Generated by Django 5.0.3 on 2024-03-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0032_rename_marque_produit_produitpharmaceutique_marque_produitpha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('Pharmaceutique', 'Produit Pharmaceutique'), ('Medicament', 'Médicament')], max_length=100),
        ),
    ]
