# Generated by Django 5.0.3 on 2024-03-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0033_alter_produit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default=None, upload_to='photos/%y/%m/%d'),
        ),
    ]
