# Generated by Django 5.0.3 on 2024-03-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0035_alter_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
    ]
