# Generated by Django 5.0.3 on 2024-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0038_alter_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='pharmacie',
        ),
        migrations.AddField(
            model_name='produit',
            name='pharmacies',
            field=models.ManyToManyField(to='app3.pharmacie'),
        ),
    ]
