# Generated by Django 5.0.3 on 2024-03-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0039_remove_produit_pharmacie_produit_pharmacies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='age',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_medecin',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_patient',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='id_produit',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='liste_produits',
            field=models.ManyToManyField(to='app3.produit'),
        ),
    ]
