# Generated by Django 5.0.3 on 2024-03-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0040_remove_ordonnance_age_remove_ordonnance_id_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='adresse_cabinet',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='num_tel',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='specialite',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
