# Generated by Django 5.0.3 on 2024-03-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0042_remove_ordonnance_prenom_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='liste_produits',
            field=models.ManyToManyField(blank=True, to='app3.produit'),
        ),
    ]
