# Generated by Django 5.0.3 on 2024-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0043_alter_ordonnance_liste_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='date',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
