# Generated by Django 5.0.3 on 2024-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0044_alter_ordonnance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='liste_produits',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='liste_produits',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
