# Generated by Django 5.0.3 on 2024-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0045_remove_ordonnance_liste_produits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='liste_produits',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='liste_produits',
            field=models.ManyToManyField(blank=True, to='app3.produit'),
        ),
    ]
