# Generated by Django 5.0.3 on 2024-03-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0048_remove_ordonnance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='qte_stock',
        ),
    ]
