# Generated by Django 5.0.3 on 2024-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0049_remove_produit_qte_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
