# Generated by Django 5.0.3 on 2024-03-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0051_rename_id_produit_commande_nom_pr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adr_mail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_mail', to='app3.login'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_adresse', to='app3.login'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='app3.login'),
        ),
    ]
