# Generated by Django 5.0.3 on 2024-03-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0053_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
    ]
