# Generated by Django 5.0.3 on 2024-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0054_alter_commande_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prenom_utilisateur',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_utilisateur',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
