# Generated by Django 5.0.3 on 2024-03-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0055_commande_prenom_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adr_mail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
