# Generated by Django 5.0.3 on 2024-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0056_alter_commande_adr_mail_alter_commande_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='nom_pr',
        ),
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
