# Generated by Django 5.0.3 on 2024-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0057_remove_commande_nom_pr_commande_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
