# Generated by Django 5.0.3 on 2024-03-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0059_commande_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
    ]
