# Generated by Django 5.0.3 on 2024-03-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0061_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='num_tel',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
