# Generated by Django 5.0.3 on 2024-03-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0062_commande_num_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='num_tel',
        ),
    ]
