# Generated by Django 5.0.3 on 2024-03-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0063_remove_commande_num_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='num_tel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
