# Generated by Django 5.0.3 on 2024-03-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0065_pharmacie_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacie',
            name='items',
        ),
    ]
