# Generated by Django 5.0.3 on 2024-03-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0066_remove_pharmacie_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='pharmacies',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='produits',
            field=models.ManyToManyField(to='app3.produit'),
        ),
    ]
