# Generated by Django 5.0.3 on 2024-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0067_remove_produit_pharmacies_pharmacie_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaCommandes',
            fields=[
                ('id_commandepharm', models.AutoField(primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(default=None, max_length=100)),
                ('prenom_utilisateur', models.CharField(default=None, max_length=100)),
                ('total', models.CharField(default=None, max_length=200)),
                ('date_commande', models.DateTimeField(auto_now=True)),
                ('ville', models.CharField(max_length=100)),
                ('adr_mail', models.CharField(default=None, max_length=100)),
                ('adresse', models.CharField(default=None, max_length=100)),
                ('num_tel', models.CharField(max_length=15, null=True)),
                ('items', models.CharField(default=None, max_length=300)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
