# Generated by Django 5.0.3 on 2024-04-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0068_pharmacommandes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacommandes',
            options={},
        ),
    ]
