# Generated by Django 5.0.3 on 2024-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0069_alter_pharmacommandes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom_utilisateur', models.CharField(max_length=100, unique=True)),
                ('prenom_utilisateur', models.CharField(blank=True, max_length=100)),
                ('adr_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=1, null=True)),
                ('adresse', models.CharField(blank=True, max_length=1, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterModelOptions(
            name='pharmacommandes',
            options={'ordering': ['-date_commande']},
        ),
    ]
