# Generated by Django 5.0.3 on 2024-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0070_customuser_delete_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100, null=True)),
                ('prenom_utilisateur', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('adr_mail', models.EmailField(max_length=254, null=True)),
                ('num_tel', models.CharField(max_length=15, null=True)),
                ('date', models.DateField(null=True)),
                ('sexe', models.CharField(max_length=1, null=True)),
                ('adresse', models.CharField(max_length=1, null=True)),
                ('role', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
