# Generated by Django 5.0.3 on 2024-04-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0071_login_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
