# Generated by Django 5.0.3 on 2024-04-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0073_alter_pharmacie_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='avatar',
            field=models.CharField(default='image/lieu.jpg', max_length=255),
        ),
    ]
