# Generated by Django 5.0.3 on 2024-04-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0074_alter_pharmacie_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='avatar',
            field=models.CharField(default='https://i.pinimg.com/564x/63/62/4e/63624efe1554c2edf839318b6db05abd.jpg', max_length=255),
        ),
    ]
