# Generated by Django 5.0.3 on 2024-04-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0076_alter_pharmacie_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='avatar',
            field=models.ImageField(default='pharmacie_avatars/lieu2.jpg', upload_to='pharmacie_avatars/'),
        ),
    ]
